version: '3.8'

services:

    frontend:
      image: ivanbrij/example-frontend
#      build: ../../../material-applications/example-frontend
      container_name: frontend
#      ports:
#      - 5000:5000
      environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/ping
      build: ../../../material-applications/example-frontend
      networks:
      - proxy-network
    backend:
      image: ivanbrij/example-backend
#      build: ../../../material-applications/example-backend
      container_name: backend
 #     ports:
 #     - 8080:8080
      environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=db-backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      build: ../../../material-applications/example-backend
      networks:
      - proxy-network
    redis:
      image: redis
      container_name: redis-cache
      networks:
      - proxy-network

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db-backend
      volumes:
        - ./data:/var/lib/postgresql/data
      networks:
      - proxy-network
    proxy:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      environment:
        - NGINX_HOST=localhost
      container_name: proxy
      networks:
      - proxy-network

networks:
    proxy-network:

